version: "3.3"
services:
    service1:
      image: service1:latest
      build: ./service1
      deploy:
        replicas: 2
      ports:
      - target: 5000
        published: 5000
        protocol: tcp
      depends_on:
      - "service2"
    service2:
      image: service2:latest      
      build: ./service2
      deploy:
        replicas: 2
      ports:
      - target: 5001
        protocol: tcp
        # nginx:
        #image: nginx:latest
        #ports:
        #- target: 80
        #published: 80
        #protocol: tcp
        #volumes:
        #- type: bind
        #source: ./nginx/nginx.conf
        #target: ./nginx/nginx.conf
